---
- hosts: all
  sudo: yes
  vars:
    statsd_npm_package_name: "git://github.com/etsy/statsd.git#4fe6aab65d9a35854b98ca365592286c9e702480"
    statsd_backends:
      - ./backends/repeater
    statsd_graphite:
      legacyNamespace: true
    statsd_support_tcp_repeater: true
    statsd_additional_options:
      repeater:
        tcp:
          enabled: true
          debug: true
          maxConnections: 10
          host: "internal-metrics.vandelay.io"
          port: 8125

  roles:
    - '../ansible-bakery'
    - statsd

  tasks:

    - meta: flush_handlers

    - name: Stop running statsd
      service: name=statsd state=stopped

    - name: Does statsd configuration exist?
      stat: path=/etc/init/statsd.conf
      register: statsd_conf

    - name: Move statsd upstart configuration, if it exists
      command: mv /etc/init/statsd.conf /opt/statsd/statsd
      when: statsd_conf.stat.exists

#    - name: Render pre/post/rm scripts
#      template: src=default
#      when: statsd_conf.stat.exists

    - name: Make fpm
      shell:
        fpm -s dir -t deb
            -p /vagrant/packages
            -n balanced-statsd-relayer
            -m mahmoud@balancedpayments.com
            -d 'nodejs >= 0.10.0'
            --version '1.0'
            --provides balanced-statsd-relayer
            --vendor dev@balancedpayments.com
            --license MIT/BSD
            --url 'https://github.com/balanced-ops'
            --deb-upstart /opt/statsd/statsd
            --description 'Balanced modification of statsd that allows a
                           local udp server with a tcp relay to our internal
                           metrics service'
            /opt/statsd
