---

statsd_enabled: yes                 # Enable the role
statsd_home: /opt/statsd            # Where to install
statsd_npm_package_name: statsd     # StatsD package name
statsd_npm_package_version:         # StatsD package version
statsd_server: ./servers/udp        # StatsD Server Protocol (UDP vs TCP)
statsd_port: 8125                   # StatsD listening port
statsd_graphiteHost: 127.0.0.1      # Hostname or IP of Graphite server
statsd_graphitePort: 2003           # Line Receiver port of Graphite (Carbon)
statsd_backends:                    # Enabled backends
- ./backends/graphite
statsd_debug: false
statsd_address: 0.0.0.0             # address to listen on over UDP or TCP
statsd_address_ipv6: false          # defines if the address is an IPv4 or IPv6 address [true or false]
statsd_mgmt_address: 0.0.0.0        # address to run the management TCP interface on
statsd_mgmt_port: 8126              # port to run the management TCP interface on
statsd_title: statsd                # Allows for overriding the process title
statsd_healthStatus: up             # default health status to be returned and statsd process starts ['up' or 'down']
statsd_flushInterval: 10000         # interval (in ms) to flush to Graphite
statsd_percentThreshold: 90
statsd_flush_counts: true           # send stats_counts metrics
statsd_graphite:
  legacyNamespace: false

statsd_additional_options: {}       # Setup additional options

statsd_support_tcp_repeater: false