---
# tasks file for ansible-apt-transport-s3

- name: Copy apt-transport-s3 file
  copy: >
    src=apt-transport-s3_1.1.2ubuntu2_amd64.deb
    dest=/tmp/apt-transport-s3_1.1.2ubuntu2_amd64.deb
    owner=root
    group=root
    mode=600

- name: Install apt-transport-s3
  command: dpkg -i /tmp/apt-transport-s3_1.1.2ubuntu2_amd64.deb

- stat: path=/usr/lib/apt/methods/s3
  register: apts3

- assert:
    that:
      - apts3.stat.exists and apts3.stat.isreg
